matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'doc/trex_emu.asciidoc'
  - 'doc/trex_ga.asciidoc'
  default_encoding: utf-8
